accounts/urls.py
from django.urls import path, include,reverse_lazy
from django.contrib.auth import views as auth_views

from tuxconfig_django import settings
from . import views
from allauth.account.views import SignupView, LoginView, PasswordResetView
from django.conf.urls import url

app_name = "account"

urlpatterns = [
    path('howitworks/', views.howitworks, name='howitworks'),
    path('login/', views.login, name='login'),
    path('profile/', views.profile, name='profile'),
    path('contribute/', views.contribute, name='contribute'),
    path('howitworks/', views.howitworks, name='howitworks'),
    url(r'^logout/$', views.logout_user,  name='logout'),

]

tuxconfig_django/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from django.conf.urls.static import static

import accounts.views
from tuxconfig_django import settings

urlpatterns = [
    url(r"^admin/", admin.site.urls),
    path('social/', include('allauth.urls')),
    path('accounts/', include('accounts.urls')),
    path('', accounts.views.index),
    path('contributor/', include('contributor.urls')),
    path('user/', include('user.urls')),
    path('vetting/', include('vetting.urls')),

] + static( settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user/urls.py
from django.urls import path, include,reverse_lazy
from django.contrib.auth import views as auth_views
from . import views
from allauth.account.views import SignupView, LoginView, PasswordResetView
from django.conf.urls import url

app_name = "user"

urlpatterns = [
    path('get_contributor/<int:repo_model>/', views.get_user_details, name='get_user_details'),
    path('get_device/<str:device_id>/<str:platform>', views.check_device_exists, name='check_device'),

]

accounts/forms.py
import logging

from django import forms
from django.contrib.auth import password_validation
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError

from user_model.models import User
from django_countries.widgets import CountrySelectWidget

accounts/views.py
import csv
import uuid, logging, json

# from org.models import Org, Membership
# from org.forms import OrgForm
from django.core.mail import send_mail, EmailMessage
from django_countries.fields import CountryField

from django.conf import settings

logging.basicConfig(filename='debug.log', level=logging.INFO)
from allauth.account.views import SignupView, LoginView
from django.contrib.auth import logout

from allauth.account.signals import user_logged_in
from django.core.signals import request_finished
from django.dispatch import receiver
from allauth.socialaccount.models import SocialAccount
from django.contrib.auth.models import Group
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required


@receiver(user_logged_in)
def login_user(sender, request, user, **kwargs):
    try:
        socialuser = SocialAccount.objects.get(user=user, provider="github")
        group = Group.objects.get(name='github')
        user.groups.add(group)
    except SocialAccount.DoesNotExist:
        pass



@login_required
def profile(request):
    if len(request.user.groups.all()) == 2:
        return render(request,"accounts/choose_signin_type.html")
    if request.user.groups.all()[0].name == "github":
        return redirect("/contributor")
    elif request.user.groups.all()[0].name == "vetting":
        return redirect("/vetting")
    else:
        return HttpResponse("Invalid user")




from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse


def logout_user(request):
    if request.user.is_authenticated:
        logout(request)
    return render(request,"accounts/index.html")


def privacy(request):
    return None

def contribute(request):
    return render(request, "accounts/how_to_contribute.html")

def howitworks(request):
    return render(request, "accounts/howitworks.html")




def index(request):
    return render(request, "accounts/index.html")

def login(request):
    return  redirect("/social/login")

accounts/templates/accounts/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes">
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.png' %}"/>
    <!-- Bootstrap CSS -->
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
      <link rel="stylesheet" href="{% static 'flags/sprite-hq.css' %}">
    <title>{% block title %}Undefined title{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark justify-content-between">
      <div class="container">
          <p class="navbar-brand img-responsive "><A href="https://www.rydalinc.org"><img style="width: 6vw" src="{% static  'rydalinc_logo_menubar.png' %}" ></a><a class="navbar-brand img-responsive text-primary navbar-dark justify-content-center" href="https://www.rydalinc.org">A Rydal inc service </a></p>
            <button class="navbar-toggler ms-auto" data-bs-toggle="collapse" data-bs-target="#navbar">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbar">
          <ul class="navbar-nav  active mx-auto me-auto">

              <li class="nav-item active">
                  <a class="nav-link" href="{% url "account:howitworks" %}">How it works</a>
              </li>
              <li class="nav-item active">
                  <a class="nav-link" href="{% url "account:contribute" %}">List your repository</a>
              </li>

              {% if request.user.is_authenticated %}
          <li class="nav-item active">
                <a class="nav-link" href="{% url "account:profile" %}">Dashboard</a>
            </li>
                  <li class="nav-item active">
                      <a class="nav-link" href="{% url "account:logout" %}">Logout</a>
                  </li>

          {% else %}
                  <li class="nav-item active">
                      <a class="nav-link" href="/">Home</a>
                  </li>
          {% endif %}


          </ul>
          
        </div>
      </div>

    </nav>

<div class="container">
  <div class="card-body">
      <div class="card-body">
          {% if messages %}
              {% for message in messages %}
                  <div class="alert alert-{{ message.tags }}">  <!-- singular -->
                      <a class="close" data-dismiss="alert">×</a>
                      {{ message|safe }}
                  </div>
              {% endfor %}
          {% endif %}
    {% block content %}

    {% endblock %}
  </div>
</div>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

  </body>
</html>

accounts/templates/accounts/choose_signin_type.html
{% extends "accounts/base.html" %} {% load crispy_forms_tags %}


{% block title %} Tuxconfig {% endblock %}
{%  load static %}



<link rel="stylesheet" href="{% static 'flags/sprite.css' %}">
{%  block heading %} <h3>Tuxconfig:</h3> {% endblock %}
{% block content %}
<h1>Choose page.</h1>
    <a href="/contributor">Contributor of code:</a>
    <a href="/vetting">Vetting products:</a>



{% endblock %}

accounts/templates/accounts/how_to_contribute.html
{% extends "accounts/base.html" %} {% load crispy_forms_tags %}


{% block title %} Tuxconfig {% endblock %}
{%  load static %}



<link rel="stylesheet" href="{% static 'flags/sprite.css' %}">
{%  block heading %} <h3>Tuxconfig:</h3> {% endblock %}
{% block content %}

<h1>Adding your repository to Tuxconfig.</h1>
<h5>Prerequisites:</h5>
<p>You must be using DKMS</p>
<p>The code you submit must be on the "master" branch.</p>
<p>Your install script should configure the Makefile for the architecture you're installing to.</p>
<p>If not i386 or x86_64 this can be determined by the "Hardware:" variable in /proc/cpuinfo</p>
<p>If not i386 or x86_64 check if the kernel is in 32 or 64 bit architecture.</p>
<p>Please note we vet each repository for malware and spyware. </p>
<br>
<h5>Adding your repository:</h5>
<p>Create a fie in your root folder called Tuxconfig</p>
<p>Sample below:</p>

    <p>device_ids="0bda:c811" #list of ids supported by this installer.</p>
    <p>cpu_ids="x86_64" #list of chipsets supported by this installer, eg x86_64, i386,BCM2711 (Raspberry pi 4)</p>
    <p>module_id="rtl8821CU" # Module id: name of your DKMS module</p>
    <p>install_command="./dkms-install.sh" # Command to install DKMS module</p>
    <p>test_command="./test_file.sh" # Exit status is 0 if your module is installed correctly.</p>


{% endblock %}

accounts/templates/accounts/howitworks.html
{% extends "accounts/base.html" %} {% load crispy_forms_tags %}


{% block title %} Tuxconfig {% endblock %}
{%  load static %}



<link rel="stylesheet" href="{% static 'flags/sprite.css' %}">
{%  block heading %} <h3>Tuxconfig:</h3> {% endblock %}
{% block content %}

    <h1>Tuxconfig device installer..</h1>
    <p>Module installs, they're a pain. You have to find your device id, get the chipset name. clone some source code. compile it into machine code, add in into your kernel with DKMS. </p>
    <p>Simple eh?</p>
    <p>Can we automate this process? Can we have a system which searches for your device online, and installs the appropriate software for it?</p>
    <p>That's what this system is all about!</p>
    <br>
    <p>I will build a debian package for this after some submissions, until then I'm happy to merge pull requests!  </p>
    <p><A href="https://www.github.com/rydal/tuxconfig-python">Front end</A> </p>
    <p><A href="https://www.github.com/rydal/tuxconfig-django">Back end</A> </p>
    <p>If you're a developer and want to submit some drivers, follow our guide at <A href="{%  url "account:contribute" %}">How to submit drivers</A> </p>
    Video walkthrough: <A href="https://www.youtube.com/watch?v=KjwHw1MYyFM">here</a>






{% endblock %}

accounts/templates/accounts/index.html
{% extends "accounts/base.html" %} {% load crispy_forms_tags %}


{% block title %} Tuxconfig {% endblock %}
{%  load static %}



<link rel="stylesheet" href="{% static 'flags/sprite.css' %}">
{%  block heading %} <h3>Tuxconfig:</h3> {% endblock %}
{% block content %}

    <h1>Easily configure your devices.</h1>
    <p>Tuxconfig is a system to automatically configure non supported devices in Linux</p>
    <p>Coders can submit code for our systems, our developers then vet the code to ensure it is safe</p>
    <br>
    <p>The application then installs the code for you.</p>
    <br>
    <p>Not happy with the driver you have? You can try the next best version for you system</p>
    <p>Developer or code vetter?</p>
    <a href="/social/login">Login</a>
    <p>End users of this application have no need to sign in to this console.</p>
    <br>
    <p><A href="{% url "account:howitworks" %}">Video walkthrough and access to source code</A></p>
    <p><A href="{% url "account:contribute" %}">How to add your repository</A></p>



{% endblock %}