tuxconfig_django/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from django.conf.urls.static import static

import accounts.views
from tuxconfig_django import settings

urlpatterns = [
    url(r"^admin/", admin.site.urls),
    path('social/', include('allauth.urls')),
    path('accounts/', include('accounts.urls')),
    path('', accounts.views.index),
    path('contributor/', include('contributor.urls')),
    path('user/', include('user.urls')),
    path('vetting/', include('vetting.urls')),

] + static( settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user/urls.py
from django.urls import path, include,reverse_lazy
from django.contrib.auth import views as auth_views
from . import views
from allauth.account.views import SignupView, LoginView, PasswordResetView
from django.conf.urls import url

app_name = "user"

urlpatterns = [
    path('get_contributor/<int:repo_model>/', views.get_user_details, name='get_user_details'),
    path('get_device/<str:device_id>/<str:platform>', views.check_device_exists, name='check_device'),

]

vetting/urls.py
from django.urls import path, include,reverse_lazy
from django.contrib.auth import views as auth_views
from . import views
from allauth.account.views import SignupView, LoginView, PasswordResetView
from django.conf.urls import url



app_name = "vetting"

urlpatterns = [
    path('edit_details/', views.add_user_details, name='vetter_details'),
    path('add_discussion_url/', views.add_user_details, name='discussion_url'),
    path('create_account/', views.account_edit, name='edit_account'),
    path('', views.dashboard, name='profile'),

]

vetting/models.py
from django.db import models

# Create your models here.
from contributor.models import RepoModel
from tuxconfig_django import settings


class SignedOff(models.Model):
    contributor = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="signed_off_to_user",
        on_delete=models.CASCADE,
    )
    id = models.AutoField(primary_key=True)
    repo_model = models.ForeignKey(
        RepoModel,
        related_name="contributor_to_repo_model",
        on_delete=models.CASCADE,
    )
    device_id = models.CharField(max_length=12)
    created = models.DateTimeField(auto_now_add=True)
    upvoted = models.BooleanField(default=False)
    downvoted = models.BooleanField(default=False)
    objects = models.Manager()

class RepositoryURL(models.Model):
    contributor = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="repository_url_to_user",
        on_delete=models.CASCADE,
    )
    id = models.AutoField(primary_key=True)
    repo_model = models.ForeignKey(
        RepoModel,
        related_name="repository_url_to_repo",
        on_delete=models.CASCADE,
    )
    discussion_url = models.CharField(max_length=240)


class VettingDetails(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        related_name="vetter_to_user",
        on_delete=models.CASCADE,
    )
    id = models.AutoField(primary_key=True)
    bio = models.CharField(max_length=240)
    email = models.EmailField(max_length=240)
    website = models.URLField(max_length=240)
    avatar_url = models.URLField(max_length=240)
    location = models.CharField(max_length=120)
    name = models.CharField(max_length=80)
    company = models.CharField(max_length=120)

vetting/forms.py
from vetting.models import VettingDetails, RepositoryURL

from django import forms
from django.forms import inlineformset_factory
from .models import RepoModel, RepositoryURL



class RepositoryURLForm(forms.ModelForm):
    class Meta:
        model = RepositoryURL
        fields = ('discussion_url',)

RepositoryURLFormset = inlineformset_factory(
    RepoModel,
    RepositoryURL,
    fields=["discussion_url",   'id'],
    extra=0,
    can_delete=False

)

class RepoForm(forms.ModelForm):

    discussion_url=forms.URLField()

    class Meta:
        model = RepositoryURL
        fields = ('discussion_url',)

class CreateUserForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField()



class UserDetailsForm(forms.ModelForm):

    class Meta:
        model = VettingDetails
        fields = ('bio','email','website','avatar_url','location',"name","company")

vetting/views.py
import json

from django.shortcuts import render, get_object_or_404

# Create your views here.
from contributor.models import RepoModel
from user_model.models import User
from vetting.forms import RepoForm, UserDetailsForm, RepositoryURLForm, CreateUserForm
from django.forms import modelformset_factory

from django.contrib.auth.decorators import user_passes_test, login_required

from vetting.models import SignedOff, VettingDetails, RepositoryURL

from django.contrib import messages
from django.http import JsonResponse


@user_passes_test(lambda u: u.groups.filter(name='vetting').exists())
def dashboard(request):
    repo_url = RepoModel()
    repo_url_form = RepoForm(instance=repo_url)  # setup a form for the parent
    AnswerFormSet = modelformset_factory(model=RepoModel, fields=['discussion_url', 'id'],
                                         form=RepoForm, extra=False, can_delete=False
                                         )

    formset = RepositoryURLForm(instance=repo_url)

    repos = RepoModel.objects.all().order_by("created")

    if request.POST:
        repo_url_form = RepositoryURLForm(request.POST)
        answer_formset = AnswerFormSet(request.POST)

        if "upvote" in request.POST:
            pk = request.POST.get("upvote")
            repo_model = RepoModel.objects.get(id=pk)
            repo_model.upvotes = repo_model.upvotes + 1
            try:
                SignedOff.objects.get(contributor=request.user, repo_model=repo_model)
                messages.error(request, "You have already voted on this repository")
            except:
                SignedOff(contributor=request.user, repo_model=repo_model, upvoted=True).save()
                repo_model.save()
        elif "downvote" in request.POST:
            pk = request.POST.get("downvote")
            repo_model = RepoModel.objects.get(id=pk)
            repo_model.downvotes = repo_model.downvotes + 1
            try:
                SignedOff.objects.get(contributor=request.user, repo_model=repo_model)
                messages.error(request, "You have already voted on this repository")
            except:
                SignedOff(contributor=request.user, repo_model=repo_model, downvoted=True).save()
                repo_model.save()

    for repo in repos:
        repo.entry_set = RepositoryURL.objects.filter(repo_model=repo)
    try:
        vetting_details = VettingDetails.objects.get(user=request.user)
    except VettingDetails.DoesNotExist:
        vetting_details = None
        messages.info(request,"Please enter your details to be recommended on our systems as a code vetter,")
    return render(request, "dashboard.html", {"repositories": repos,"vetting_details" : vetting_details })


@user_passes_test(lambda u: u.groups.filter(name='vetting').exists())
def add_user_details(request):
    if request.POST:
        user_details = UserDetailsForm(request.POST)

        if user_details.is_valid():
            try:
                vetting_details = VettingDetails.objects.get(user=request.user)
                vetting_details.bio = user_details.cleaned_data.get("bio")
                vetting_details.website = user_details.cleaned_data.get("website")
                vetting_details.email = user_details.cleaned_data.get("email")
                vetting_details.avatar_url = user_details.cleaned_data.get("avatar_url")
                vetting_details.location = user_details.cleaned_data.get("location")
                vetting_details.company = user_details.cleaned_data.get("company")
                vetting_details.name = user_details.cleaned_data.get("name")
                vetting_details.save()
            except VettingDetails.DoesNotExist:
                vetting_user = user_details.save(commit=False)
                vetting_user.user = request.user
                vetting_user.save()
        else:
            messages.error(request, json.dumps(user_details.errors))
    try:
        vetting_details = VettingDetails.objects.get(user=request.user)
    except VettingDetails.DoesNotExist:
        vetting_details = None
    if vetting_details is not None:
        user_details = UserDetailsForm(instance=vetting_details)
    else:
        user_details = UserDetailsForm()
    return render(request, "vetter_form.html", {"user_details": user_details})

from django.http import HttpResponse

@login_required
def account_edit(request):
    form = CreateUserForm()
    if request.user.is_superuser: # just using request.user attributes
        if request.POST:
            form = CreateUserForm(request.POST)
            if form.is_valid():
                email = form.cleaned_data.get("email")
                password = form.cleaned_data.get("password")
                try:
                    User.objects.get(email=email)
                    messages.error(request,"User already exists")
                except User.DoesNotExist:
                    u = User.objects.create_user(email,password)
                    u.save()
                    messages.success(request,"User created")
            else:
                messages.error(request,"Form not valid")



        return render(request,"create_user_form.html",{"form" : form })
    else:
        return HttpResponse(request,"Not a superuser")

vetting/templates/create_user_form.html
{% extends "accounts/base.html" %} {% load crispy_forms_tags %}


{% block title %} Tuxconfig {% endblock %}
{%  load static %}



<link rel="stylesheet" href="{% static 'flags/sprite.css' %}">
{%  block heading %} <h3>Dashboard:</h3> {% endblock %}
{% block content %}


    <h1>Sign off on module:</h1>
    <form method="post" id="repo_form">
    {%  csrf_token %}
    {{  form }}
    <input type="submit" class="btn btn-primary" value="Add user">


    </form>

{% endblock %}

vetting/templates/dashboard.html
{% extends "accounts/base.html" %} {% load crispy_forms_tags %}


{% block title %} Tuxconfig {% endblock %}
{%  load static %}



<link rel="stylesheet" href="{% static 'flags/sprite.css' %}">
{%  block heading %} <h3>Dashboard:</h3> {% endblock %}
{% block content %}

    <a href="{%  url "vetting:vetter_details" %}">Edit vetting details</a>
    {%  url "vetting:vetter_details" %}

    <h4>Sign off on module:</h4>
    <form method="post" id="repo_form">
        {{ repositories.management_form }}
        {%  for repo in repositories %}

            {%  if repo.upvotes > 4 %} <p class="alert alert-success">Verified as safe</p>
            {%  elif repo.downvotes > 4 %} <p class="alert alert-danger">Verified as unsafe</p>{%  else %}
                <p class="alert alert-warning">To be verified</p>
            {%  endif %}
            <a href="https://www.github.com/{{  repo.git_username }}/{{  repo.git_repo }}/commit/{{ repo.git_commit }}" target="_blank" >https://www.github.com/{{  repo.git_username }}/{{  repo.git_repo }}/{{  repo.git_commit }}</a>
            <p>Module name: {{ repo.module_name }}</p>
            <p>Upvotes: {{  repo.upvotes }}</p>
            <p>Downvotes: {{  repo.downvotes }}</p>
            <p><A href="{{ repo.discussion_url  }}">{{ repo.discussion_url  }}</A></p>
            {{ repo_url_form }}

            <br>
            <button type="submit" value="{{  repo.id }}" name="upvote">
                <img src="{% static "up_button.png" %}" />
            </button>
            <button type="submit" value="{{  repo.id }}" name="downvote">
                <img src="{% static "down_button.png" %}" />
            </button>

            <br>

        {%  empty %}
            <p class="alert alert-warning">No modules to sign off right now</p>

        {%  endfor %}

        {%  csrf_token %}


    </form>

{% endblock %}

vetting/templates/user_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% extends "accounts/base.html" %} {% load crispy_forms_tags %}


        {% block title %} User {% endblock %}
        {%  load static %}



        <link rel="stylesheet" href="{% static 'flags/sprite.css' %}">
        {%  block heading %} <h3>Dashboard:</h3> {% endblock %}
        {% block content %}

            <h1>Add your details:</h1>
                <form method="post">
                {{  user_details }}

                {%  csrf_token %}
                <button class="btn btn-primary">Update details.</button>
                </form>

        {% endblock %}
    </title>
</head>
<body>

</body>
</html>

vetting/templates/vetter_form.html
{% extends "accounts/base.html" %} {% load crispy_forms_tags %}


{% block title %} eh? {% endblock %}
{%  load static %}



<link rel="stylesheet" href="{% static 'flags/sprite.css' %}">
{%  block heading %} <h3>Dashboard:</h3> {% endblock %}
{% block content %}

    <h1>Your details:</h1>
    <p>These will be displayed to user upon a successful install.</p>
    <form method="post">
    <table>
        <tr>
            <td>
                Name:
            </td>
            <td>
                {{  user_details.name }}
            </td></tr>
        <tr>
            <td>
                Company:
            </td>
            <td>
                {{  user_details.company }}
            </td></tr>
        <tr>
        <td>
            Bio:
        </td>
        <td>
    {{  user_details.bio }}
    </td></tr>
    <tr><td>
        Website:
    </td><td>
        {{  user_details.website }}
    </td></tr>
    <tr><td>
        Email:
    </td><td>
        {{  user_details.email }}
    </td></tr>
    <tr><td>
        Avatar url:
    </td><td>
        {{  user_details.avatar_url }}
    </td></tr>
        <tr><td>
            Location:
        </td><td>
            {{  user_details.location }}
        </td></tr>
    </table>

    {%  csrf_token %}
        <input type="submit" class="btn btn-primary" value="Submit details">

    </form>


{% endblock %}